### ISSUE TITLE
Code from Language Reference not working

### ISSUE THREAD

**Issue by stefandd** [aardappel/lobster#108]
```
def function_type(int) -> int
def g(f:function_type): return 1 + f(2)
```
as discussed in [http://aardappel.github.io/lobster/language_reference.html](url) returns the error:
.lobster(1): error: identifier expected, found: int

**Comment by aardappel** [comment]
Ah yes, there currently needs to be e.g. `def function_type(a:int) -> int`. We could in theory support the syntax without an identifier, but in the current syntax the parser only knows its a function type one it sees there is no function body.. so I guess for now we'll just fix the docs: https://github.com/aardappel/lobster/commit/c7e82af7b741b9d65a3898c107bd566b607aa160
