### ISSUE TITLE
Parser error on negative case values in switch statements

### ISSUE THREAD

**Issue by stefandd** [aardappel/lobster#115]
```
let game_stage:int = -1

switch game_stage:
    case -1:
        pass()
    case 0:
        pass()
```

This produces a the error .lobster(4): error: illegal start of expression: -

**Comment by aardappel** [comment]
Fixed, thanks! https://github.com/aardappel/lobster/commit/6e4751348e23c2ee3dd50701cfb7dcab2a4039dc
