### ISSUE TITLE
Bug in vector operations

### ISSUE THREAD

**Issue by stefandd** [aardappel/lobster#118]
let x = xyz_i{1, 0, 0}
print 3 * x // x * 3 works

produces the erro .lobster(2): error: can't use "*" on "int" and "xyz_i"

**Comment by aardappel** [comment]
That's an intentional limitation that should probably be documented for the moment. It was there to not explode the number of VM vector operations. Though I guess it just needs extra versions of `-`, `/` and `%`, the rest can be swapped. Should eventually be made possible, of course.

**Comment by stefandd** [comment]
I don't think you'd need extra operators for `/` or `%` because either would be ill-defined if the number was the left operand! I think you'd only need an extra version of the `-` then.

**Comment by aardappel** [comment]
Why? `4 / xy { 2, 1 }` could result in `xy { 2, 4 }`, no different from `-`. The other way around is just more natural to read, since you start with a vector already.

**Comment by stefandd** [comment]
I respectfully disagree since the operations should make some mathematical sense. For `4 / xy { 2, 1 }` to be defined it would have to be the same as 4 * (1 / xy { 2, 1}). The inverse of such a vector is, at least mathematically, not defined. At least in these cases (/, and %) an error message would be much more forgivable from a user point of view.

**Comment by aardappel** [comment]
This is fixed, nowadays `scalar op vector` works
