### ISSUE TITLE
Sublime Text support

### ISSUE THREAD

**Issue by RobotCaleb** [aardappel/lobster#12]
I've got a 90% solution for building with Sublime Text. (On windows)

The problem I'm running into is rooted in compiler errors. The output for an error looks like:
`file.lobster(2): error: unknown identifier: foo`

When parsed I get a filename of `file.lobster`, which is mostly okay. However, in order to invoke the compiler it has to either live on my path  or I have to specify lobster.exe's path as the working directory. (otherwise we get `can't open file: sdt.lobster`)

If I specify the working directory as lobster.exe's path, I can't properly navigate to source files with errors as it tries to open them from the working directory.

If I add lobster.exe's path to my PATH I am still unable to build due to `can't open file: std.lobster`.

The easiest solution I see is to have the compiler output absolute path to file in errors.

It works fine if I don't try to use Sublime Text's error location opening to jump to the offending line. That is, I can compile (and even run if no errors) if I avoid the functionality.

**Comment by aardappel** [comment]
Is this still an issue?
