### ISSUE TITLE
Clarify introduction senctence to the programming language

### ISSUE THREAD

**Issue by mclillill** [aardappel/lobster#122]
First senctence on the website is:

> Lobster is a programming language that tries to combine the advantages of **very** static typing and **memory management** with a very lightweight, friendly and terse syntax, by doing most of the heavy lifting for you.

I trip on the **very** before static typing. What is meant by this?
Additionally unclear to me is the mention of memory management. Is it automatic or also **very static**?

**Comment by aardappel** [comment]
it is meant to indicate "more static than the average statically typed programming language" or similar. And yes the memory management is also somewhat static (most languages it is entirely dynamic).

So maybe.. `the advantages of static typing and static memory management` to keep it simple ?

**Comment by mclillill** [comment]
I think that's easier to understand, yes.

**Comment by aardappel** [comment]
You're not supposed to close an issue until its been fixed :)

**Comment by aardappel** [comment]
ok, fixed

**Comment by mclillill** [comment]
@aardappel Sorry :-)
