### ISSUE TITLE
Where to find third-party libraries

### ISSUE THREAD

**Issue by FeldrinH** [aardappel/lobster#130]
Looking through the documentation and other Lobster-related materials, I could not find answers to the following questions:

Are there any existing third-party libraries available for Lobster?
If there are, where and how to find them?

It feels like these are questions that should have some sort of answer in the official docs.

**Comment by aardappel** [comment]
There currently aren't any.. Lobster is very much a "batteries included" kind of system, all the currently included libraries (mostly gamedev oriented) you can find here: http://aardappel.github.io/lobster/builtin_functions_reference.html

A third party library, if it would exist, could take two forms: a pure lobster one, which would be easy just to copy into your project, or bindings to a native library, which could be done modularly, but would need some additional facilities.
