### ISSUE TITLE
Language tools for M1 Mac and macOS?

### ISSUE THREAD

**Issue by ornamentist** [aardappel/lobster#139]
I've tried running the pre-built macoS-x64 lobster download on an M1 Mac but it crashes when run.  

I've also downloaded the source with the included XCode project. I've managed to avoid XCode for the whole time I've been using a Mac so I need to do some reading on how to build with that tool. I'll add comments to this issue as I learn more.

**Comment by aardappel** [comment]
Yes, would be good to know where it crashes.

One thing is that if you try to run some Lobster code directly (not with `--cpp`), it will JIT the code to x86. I can imagine that somehow not working on the M1. That should be apparent in a stack trace.

**Comment by erwincoumans** [comment]
see also https://lists.nongnu.org/archive/html/tinycc-devel/2022-01/msg00004.html

**Comment by aardappel** [comment]
I currently don't have an M1 machine to try this on.. ideally it would JIT straight to ARM, which it does have an implementation for.

**Comment by aardappel** [comment]
This is stale, libtcc in Lobster now supports running on M1
