### ISSUE TITLE
Add link to syntax file for lite-xl editor

### ISSUE THREAD

**Issue by franko** [aardappel/lobster#143]
I am the author of [Lite XL](https://github.com/lite-xl/lite-xl/), an lightweight editor for programmers derived from [rxi/lite](https://github.com/rxi/lite/).

I am beginning to explore the Lobster programming language and up to now I find it really amazing. Thank you for developing such a refreshing, simple and yet efficient programming language.

I wrote a syntax support file for the Lobster language to be used with Lite XL. It can be found now in the [Lite XL plugins](https://github.com/lite-xl/lite-plugins) page.

It was quite easy to implement. Here a screenshot of a code sample:

![image](https://user-images.githubusercontent.com/433545/128548458-5226e756-eef8-43e3-b8c5-34c87059c7ad.png)

I decided to highlight `if`, `else`, `while` and `for` as keywords even if they are not because they implement basic control flow structures.

Thank you!

PS: I think in the Lobster Language Reference page you forgot to include `fn` among the keywords.

**Comment by aardappel** [comment]
Thanks for the kind words :)

Cool you're continuing the work of Lite, the syntax highlighting looks good! Linked to your editor from the docs, see https://github.com/aardappel/lobster/commit/1a3634fbc486971c9dc105b7dd6539e359bd3a1d

What about running code from the editor, showing output, and highlighting / jumping to errors? :)

Also fixed the missing `fn` :)

**Comment by franko** [comment]
> Cool you're continuing the work of Lite, the syntax highlighting looks good! Linked to your editor from the docs, see [1a3634f](https://github.com/aardappel/lobster/commit/1a3634fbc486971c9dc105b7dd6539e359bd3a1d)

Thank you, I am proud to have the Lite XL name on the Lobster page!

> What about running code from the editor, showing output, and highlighting / jumping to errors? :)

For this there is the console plugin of our grand master, rxi. I have just adapted the plugin for Lite XL, it can be found here:

https://github.com/franko/console

**Comment by franko** [comment]
No reason, to keep this open. Thank you.
