### ISSUE TITLE
"return from program" not exiting program.

### ISSUE THREAD

**Issue by MortimerSnerd** [aardappel/lobster#148]
I'm on commit  4d03557d32163e18e4aa8d3dedcc231177f537ca which only seems to be missing some sample and cmake commits.  I've only been able to try this on Linux so far.

I noticed I was getting messages printed from `fatal()` calls, but the program was continuing to run.  Example:
```lobster
import std

print("oi")
fatal("fatal error")
print("vey")  // This gets printed
```

The same happens with a bare "return from program" at the end of a function.

**Comment by aardappel** [comment]
Sorry for not addressing this for so long.. Just was able to fix, thanks for reporting! This was actually broken for a while, but because `return from program` only gets used on fatal errors I never noticed :)
