### ISSUE TITLE
How are cycles solved in Lobster?

### ISSUE THREAD

**Issue by hubertpnj** [aardappel/lobster#151]
According to the website: "Reference Counting with **cycle detection at exit**". Does that mean **at program exit**? I don't believe so, as it would mean that doubly-linked list were unusable without eating memory till the end of the program.

**Comment by maddanio** [comment]
Interesting. Raw pointers are the one thing that i will have a hard time letting go of should i ever leave c++ for rust. Its so often that i build hierarchical structures with cross pointers, and i keep wondering how i could solve it in rust. One of these days i will have to find out:)
