### ISSUE TITLE
Lobster font

### ISSUE THREAD

**Issue by davelab6** [aardappel/lobster#16]
Would be nice to use https://www.google.com/fonts/specimen/Lobster for branding this :)

**Comment by aardappel** [comment]
I agree, that be appropriate :)
Haven't done much "branding" so far though.

**Comment by Asmageddon** [comment]
That would be a bit painful to read. Maybe included in the distribution, and by default used only for a title or logo or something.

**Comment by aardappel** [comment]
Oh yeah, I am sure he meant as a logo :)
