### ISSUE TITLE
64-bit build?

### ISSUE THREAD

**Issue by binji** [aardappel/lobster#17]
I finally got a 32-bit linux build working with symlink magic -- but I'd much rather just build a 64-bit version. How much work is it to switch over? I wouldn't mind taking a look if you'd consider taking the PR. :)

**Comment by gwvo** [comment]
I could make an "easy" 64bit port which would just bloat up memory used by Lobster objects by 2x.. which is obviously undesirable. But I guess for basic experimentation that be fine.

I'd love a PR, but there are a few potential gotchas.. I don't mind having a look myself tomorrow.

**Comment by aardappel** [comment]
Ok, made a bunch of commits to fix up the linux build. It should now build out of the box with the native arch, see http://htmlpreview.github.io/?https://raw.githubusercontent.com/aardappel/lobster/master/lobster/docs/implementation.html

**Comment by binji** [comment]
Awesome, thanks!

**Comment by binji** [comment]
I was able to build this and run it. Closing!

**Comment by gwvo** [comment]
Cool.. let me know what you find :)
