### ISSUE TITLE
hotfix support

### ISSUE THREAD

**Issue by Xarvie** [aardappel/lobster#171]
is it support runtime compile？ like  code.compile(“./main.codefile”);
hot reload for mobile game bug fix.

**Comment by Xarvie** [comment]
Oh, it’s support.

**Comment by aardappel** [comment]
Do note when you use `compile_run_file`, that code essentially runs in its own VM, so it's not suitable for hot-patching unless you always run the code to be patched separately from the "launcher".

**Comment by Xarvie** [comment]
> 

thanks, got it
