### ISSUE TITLE
Version of Open GL required for Lobster

### ISSUE THREAD

**Issue by briviere** [aardappel/lobster#19]
Hello 

Does lobster require OpenGL 1.3?

thanks

Brian

**Comment by aardappel** [comment]
Depends on platform, but it mostly requires 2.1 or up.

What platform are you on? Any particular error you're getting?

**Comment by briviere** [comment]
The platform I'm on is:

Linux 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64
x86_64 x86_64 GNU/Linux

brian

**Comment by aardappel** [comment]
FYI, it nowadays requires OpenGL 3.2 (desktop), ES 3.0 (mobile) or WebGL 2.
