### ISSUE TITLE
Console input?

### ISSUE THREAD

**Issue by 0xEquinox** [aardappel/lobster#195]
Is there user input for the console implemented for lobster yet? I can't find it anywhere in the docs or in the stdl.

**Comment by aardappel** [comment]
There is:

<html>
<body>


get_line(prefix:string) -> string | reads a string from the console if possible (followed by enter). Prefix will be printed before the input
-- | --



</body>
</html>

**Comment by aardappel** [comment]
That is pretty minimal.. but I guess for a language focused on games that was all that was ever needed :)
