### ISSUE TITLE
Specifying function return types results in an error

### ISSUE THREAD

**Issue by AntonBogun** [aardappel/lobster#197]
The following code
```
def f() -> [int],int:
    let a=[1]
    return a,1
def f2(l) -> void:
    print(l)
f2(f())
```
results in the error
``run.lobster(3): error: `return` requires type `([int], int)`, got `[int]` ``
However, removing `-> [int],int` results in no error and the expected behaviour - printout of `[1]`.

**Comment by aardappel** [comment]
Ahh.. that's because you're calling it in a way that takes only 1 return value, which then removes the `1` and then afterwards complains about it :)

**Comment by AntonBogun** [comment]
So not intended?

**Comment by aardappel** [comment]
No, this should compile.

**Comment by aardappel** [comment]
Should be fixed here: https://github.com/aardappel/lobster/commit/76fa822cb297de5791fb907e4950a7ec346b9eef
