### ISSUE TITLE
remove() does not handle references correctly

### ISSUE THREAD

**Issue by AntonBogun** [aardappel/lobster#198]
The code
```
let l=[[1],[2]]
l.remove(0,2)
print(l)
```
results in a post-execution warning:
`LEAKS FOUND (this indicates cycles in your object graph, or a bug in Lobster)`
`_-1_ = [2]`

Note that the same applies when using strings, but not integers, which leads me to believe that this is an issue only with referenced values.

**Comment by aardappel** [comment]
This should fix it.. https://github.com/aardappel/lobster/commit/780df79b481181cde42133323dcf09aea96d2026
It actually improves default arg handling for builtin functions generally.

**Comment by aardappel** [comment]
Fixed here: https://github.com/aardappel/lobster/commit/8071024d25b265a7534ecb69dc413f99a313143a
