### ISSUE TITLE
builtin_functions_reference does not update automatically

### ISSUE THREAD

**Issue by AntonBogun** [aardappel/lobster#201]
The new change of write_file being able to write to a relative path was not automatically mirrored to the docs. I think an automatic doc update at each commit that influences the functions wouldn't be a bad idea.

**Comment by aardappel** [comment]
Not sure how we'd do that automatically.. it requires `lobster.exe` to be run with a particular flag.

**Comment by AntonBogun** [comment]
Could a github action be able to do this?

**Comment by aardappel** [comment]
I don't believe they can add to the commit they're testing..
