### ISSUE TITLE
music.c: Fails to compile with empty union.

### ISSUE THREAD

**Issue by dbaileychess** [aardappel/lobster#205]
Grabbed the latest source and try to build on Windows (VS 2022, Release X64) and it fails to compile with:

```
lobster\dev\external\SDLMixer\music.c(120,5): error C2016: C requires that a struct or union have at least one member
```

Appears I don't have any of [these](https://github.com/aardappel/lobster/blob/master/dev/external/SDLMixer/music.c#L84-L120) defined that leads to the empty union. I can probably get the necessary files, but either the Docs should specify how, or something is not included correctly by default.

Steps:

```
git clone 
cd dev
cmake -DCMAKE_BUILD_TYPE=Release
```

Opened  `dev/Lobster.sln` in VS2022, switched to `Release` and `Rebuilt Solution`

**Comment by aardappel** [comment]
Don't use CMake on Windows.. there's an already made VS solution in dev/lobster that has lots of custom flags set that aren't in CMake (never tried building with that on Windows).

See also: https://aardappel.github.io/lobster/getting_started.html
