### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by JonesAndrew** [aardappel/lobster#21]
This might be something I'm doing wrong, but using the cmake file I got this error:
```
/Users/andrew/lobster/dev/src/platform.cpp:186:9: error: 'CreateStandardAlert' was not declared in this scope
         CreateStandardAlert(kAlertStopAlert, CFSTR("Error:"), sr, nullptr, &alertDialog);
/Users/andrew/lobster/dev/src/platform.cpp:187:9: error: 'RunStandardAlert' was not declared in this scope
         RunStandardAlert (alertDialog, nullptr, nullptr);
```

**Comment by aardappel** [comment]
Looks like you're on OS X.. I just tried to build on OS X, and it worked for me.

Also, `CreateStandardAlert` it complains about for me is on line 344, which means you are compiling an older version? Can you try with the latest version?

What version of Xcode? Any other changes?

**Comment by JonesAndrew** [comment]
Oh ya, my bad. I tried checking out the latest released version to see if that was my problem and I forgot to checkout the latest version again. I'm getting the error on line 344 now. My Xcode version is 9.1 and clang is Apple LLVM version 9.0.0 (clang-900.0.38).

**Comment by aardappel** [comment]
This appears to be the answer: https://stackoverflow.com/questions/3783540/initcursor-createstandardalert-runstandardalert-not-declared-in-scope-wh

The Xcode project that comes with lobster is set to 32-bit, you probably upgraded it to 64-bit as you opened it. 

Let me see if I can make it work on 64-bit though.

**Comment by JonesAndrew** [comment]
Sorry, I missed all the stuff about 32-bit. That solved my problems, thanks!

**Comment by aardappel** [comment]
For what it's worth, I just made it work with 64-bit out of the box: https://github.com/aardappel/lobster/commit/16e1ba0ce02af7b4cc4154bd72e8df52c10adf8d

**Comment by JonesAndrew** [comment]
Oh, awesome! Thanks.
