### ISSUE TITLE
UNIX/Linux/Mac/BSD support?

### ISSUE THREAD

**Issue by gcasa** [aardappel/lobster#237]
This language looks really great and inspiring.   I love all of its concepts.  It would be nice to have versions for OSs beyond just windows.  if I can be of assistance with this let me know.  GC

**Comment by aardappel** [comment]
What makes you think this is Windows only? The docs talk about the 6 platforms this builds on (Win/Lin/Mac/iOS/Android/Web), and our CI tests 5 of those.

**Comment by aardappel** [comment]
https://aardappel.github.io/lobster/implementation.html

CI e.g. https://github.com/aardappel/lobster/actions/runs/4711582984

**Comment by gcasa** [comment]
Under RELEASES it says "Windows release"

**Comment by aardappel** [comment]
Well, maybe read some docs before concluding anything from just the releases page? :)

You should generally build this on your platform, but Windows users are a) not very used to that, and b) constitute the largest segment of users, so hence a build is provided.

We may do that eventually for more platforms, but its early days.

**Comment by gcasa** [comment]
I apologize for misunderstanding.  I will try to build under macOS and Linux and let you know if I see any issues.

**Comment by aardappel** [comment]
The releases will now include Linux & Mac at least

**Comment by aardappel** [comment]
https://github.com/aardappel/lobster/releases
