### ISSUE TITLE
[enhancement] shebang support in lobster scripts

### ISSUE THREAD

**Issue by 482migs** [aardappel/lobster#241]
i reckon that adding shebangs to lobster would make the whole experience just a little easier. a shebang (for those who don't know) is a line at the start of a script pointing the shell to where the interpreter is (`#! path_to_interpreter [args]`). currently, if you try to add a shebang to your script, you get an error looking like this:
```
hello_world.lobster(1): error: illegal token: '#'
```

i feel like this would enhance the development experience a lot.

**Comment by aardappel** [comment]
Here you go: https://github.com/aardappel/lobster/commit/3d3321c048fec8910a6b3dd9637c2acd8a577578

**Comment by 482migs** [comment]
thank you!
