### ISSUE TITLE
Android buld fail

### ISSUE THREAD

**Issue by milen-prg** [aardappel/lobster#248]
with error:

Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @4210fcab

**Comment by milen-prg** [comment]
I try not to run the project in Android Studio, but only to build APK from menu Build. And it was successful.

BUT: When I try to start the produced app-debug.apk in emulator and on modern real device I see this error:

SDL HIDAPI ERROR... couuldn't find libhidapi.so

**Comment by aardappel** [comment]
I have no idea how to fix such errors. Android always seems to build fine on CI: https://github.com/aardappel/lobster/actions/runs/4840880933/jobs/8626799508 so your best bet would be to see how your setup differs from that?
