### ISSUE TITLE
Namespace + "import gl" causes an error

### ISSUE THREAD

**Issue by morew4rd** [aardappel/lobster#254]
File 'repro.lobster':
```lobster
namespace test
import gl

print "hello"
```
Running this file fails with 
```
gl.lobster(61): error: unknown field/function reference `map`
```
**Notes:**
- Importing it from another file and running that file causes the same issue.
- After removing/commenting out either `namespace` or `import` statements, code works fine.
- After moving `import` on top of the file (i.e., above the `namespace`), code works fine

**Comment by aardappel** [comment]
Ah yes, the namespace is active until the end of the file, and since the imports don't have their own namespace, it is affecting them. The solution is to shelve the current namespace during an import.

**Comment by morew4rd** [comment]
This sets my personal record for the time it took the repo owner fixing a bug fixed after me filing it: 9 minutes ❤️

**Comment by aardappel** [comment]
I find that if its something small I understand how to fix, its quicker to just fix it then to return to it later :)
