### ISSUE TITLE
[Question] Will there ever be an LSP?

### ISSUE THREAD

**Issue by Mezo-hx** [aardappel/lobster#261]
as the title says, will there ever be an LSP? for IntelliSense, finding and typing definitions and finding references.

i

**Comment by aardappel** [comment]
https://github.com/aardappel/lobster/pull/239
@ewoudje :)

**Comment by Mezo-hx** [comment]
I'm actually not that sure on how to set it up, I never really tinkered much with VSCode extensions and such so I'm pretty lacking in that area.

**Comment by aardappel** [comment]
Well, that link shows it is in progress.. would not recommend trying to use it at this stage unless you want to help with development of it.

**Comment by Mezo-hx** [comment]
oh, alright, gotcha 👍

**Comment by aardappel** [comment]
The above PR has been merged.. Please try it out and give @ewoudje some feedback.
