### ISSUE TITLE
gl_create_texture doesn't support cubemaps

### ISSUE THREAD

**Issue by Dheu3** [aardappel/lobster#263]
```
gl_create_texture(buf, texture_format_cubemap)
```

fails to create texture and results in GL errors.

looks like in the binding if the variable `ys` is divided by 6 before being passed to `CreateTexture` it will work as expected

**Comment by aardappel** [comment]
The fix is probably a bit more complicated because `CreateTexture` expects 6 buffers that follow eachother in memory, and the current construction code seems to simply create an interleaved 2D array.. but that should not be hard to fix.

I'll have a look.

**Comment by aardappel** [comment]
Fixed here: https://github.com/aardappel/lobster/commit/2edd07ac92f405cee2001ac9c4346af1a2887823
