### ISSUE TITLE
Enable CUBE_MAP_SEAMLESS?

### ISSUE THREAD

**Issue by Dheu3** [aardappel/lobster#264]
```
glEnable(GL_TEXTURE_CUBE_MAP_SEAMLESS)
```

Available if the GL version is 3.2 or greater

**Comment by aardappel** [comment]
Hadn't heard of this one.. seems that should simply be on always, right?

**Comment by Dheu3** [comment]
Yeah, not an expert, but I don't see a down side

**Comment by aardappel** [comment]
Ok, always on here: https://github.com/aardappel/lobster/commit/e3832678e9245c6a2ca6937f74652e78ca27b2c7
