### ISSUE TITLE
 scan_folder()

### ISSUE THREAD

**Issue by NoidoDev** [aardappel/lobster#271]
So, I really tried to use scan_folder to read a dir, and I don't get it. 
What makes this even worse, is that I don't get any error and it doesn't print anything (which I tried for debugging). On error it returns "nil", which can't be printed, instead of "-1", no "false". 

I'm on Linux (Arch based). Even if it was related to the dirs it knows, then it should at least return some error. I didn't find more information. 

lobster version 2023-10-19T16:36:12-07:00|7b2026bf
```
var path = "/run/media/.../"
print scan_folder(path)
var frames = scan_folder("/run/media/...")
print type_string(frames)
```

After finding the description on Default Directories here https://aardappel.github.io/lobster/command_line_usage.html - I tried some more things. Making addition dirs in those directories, trying relative paths. Idk, nothing works.

```
print scan_folder("Foo")
var frames = scan_folder("Frames", "/somePath/")
print frames
```

**Comment by aardappel** [comment]
As the API indicates, `nil` is indeed the error value for when a directory cannot be scanned. There is no further error text in this API.

On my Ubuntu, `print scan_folder("/")` gives me a list of all root folder names, as expected.
There is also `samples/demos/dirbrowse.lobster` which uses this API, which you can try, and runs fine for me on Ubuntu.

So either your paths are indeed incorrect (not sure what the `...` stands for in your case), or you have a permission problem on your system to that folder?

**Comment by NoidoDev** [comment]
Thanks. I tried it again and it didn't work. No, this isn't about permissions. The ... above was just one dir on my name, I should've used <somedir>. `print scan_folder("/home/<myhomedir>")` didn't work in that file. But I made an explicit testfile test.lobster and yes there it works. 

I tested if the problem is related to something like the import of gui, texture or std - but I think it somehow does some checks first before it executes the print function. Despite the print coming before most of the other code.

**Comment by NoidoDev** [comment]
Edit: My fault. Sorry.  I didn't think in terms of a compiled language. It only occurred to my that my way of testing that function made no sense, if the program fails down the line because it's unfinished.
I was still trying out how to get the data from the dir and then use it later in the program. In an interpreted language it would've shown the error earlier.

**Comment by NoidoDev** [comment]
And I'm running directly into the next problem, maybe this language just isn't for me: 
In my first little program I put in` let piclist = ["01.jpeg", "03.jpeg", "05.jpeg", "07.jpeg",` and used pop() to get the elements.
In my new program I can't get the result of scan_folder to do the same thing: error: pop` (1st argument) requires type `[]`, got `[string]? while `vector[0]` also doesn't work, neither any of the other build-in functions I tried.

**Comment by aardappel** [comment]
The result of `scan_folder` is possibly `nil`, so you need to check the result with `if` before you access it.

See e.g. https://aardappel.github.io/lobster/type_checker.html
