### ISSUE TITLE
Error when setting an index of a vector

### ISSUE THREAD

**Issue by jinyus** [aardappel/lobster#272]
This code doesn't work:
```python
let nums = []::[int]

vector_capacity(nums, 5) 

for(5) i:
    nums[i] = 0 

print(nums)
```

` demo.lobster(6): error: '=' (right argument) requires type '[int]', got 'int'`
<br>

I am aware that this can be done with `insert(xs:[any], i:int, x) -> [any]` but IIUC, it should be possible  according the docs:

https://github.com/aardappel/lobster/blob/ec32e23edf752f3ffd5b397f02bca79e479f0816/docs/source/language_reference.md?plain=1#L159

<br>
It's used here as well: 

https://github.com/aardappel/lobster/blob/ec32e23edf752f3ffd5b397f02bca79e479f0816/docs/source/language_reference.md?plain=1#L282

**Comment by aardappel** [comment]
You want `[]::int` because what comes after `::` is the element type, not the whole vector type.

Maybe a bit confusing, but generally better not to have to write `[]` always.

**Comment by jinyus** [comment]
Thanks, easy mistake to make.

**Comment by jinyus** [comment]
It seems this has to be done with `insert`. Getting an index out of range error now:

`VM error (demo.lobster): index 0 out of range 0 of: []`

**Comment by aardappel** [comment]
As the name says, it reserves capacity (such that it doesn't have to reallocate), not initialized elements.

You'd normally just use `push` in a loop like that, rather than `insert`.

The idiomatic way to make a `0` initialized list is `let nums = map(5): 0`

**Comment by aardappel** [comment]
I wouldn't use `vector_capacity` unless you're trying to do something performance sensitive.. `map` does `vector_capacity` for you.

**Comment by jinyus** [comment]
> I wouldn't use `vector_capacity` unless you're trying to do something performance sensitive.. `map` does `vector_capacity` for you.

Thanks for the heads up. I'm adding lobster to my [data processing benchmark](https://github.com/jinyus/related_post_gen)

**Comment by aardappel** [comment]
Ah cool. I doubt it will do well on any benchmarks currently, its decently fast but won't compete against the actually optimized languages on your list. Be sure to try both jit and compiled mode (latter some 3x faster in my testing). Show me the code once you've made it, I can check it for anything that really holds speed back.

**Comment by jinyus** [comment]
Just finished the initial impl: https://github.com/jinyus/related_post_gen/pull/418
