### ISSUE TITLE
Building on OSX: No member named 'string_view' in 'flatbuffers::String'

### ISSUE THREAD

**Issue by joerimmer** [aardappel/lobster#30]
Hey, C/C++ noob here - saw the post on HN and decided to give Lobster a shot. I've built stuff from source before, but for whatever reason I'm having issues getting this to work.

I opened up the XCode project and tried to build with the command line target, which failed with 10 of the following build-time errors across disasm.h and vm.cpp:
/Users/joerimmer/Documents/Dev/Lobster/lobster/dev/src/lobster/disasm.h:30:54: No member named 'string_view' in 'flatbuffers::String'

Trying to target lobsterapp results in the same, with an LLVM segfault for good measure. lobster_ios fails to build tonative.cpp in addition to the above.

I know that Apple's LLVM/clang is a bit behind the curve on new C++17 features, which I gather string_view might be? It seems like using string_view in Lobster was added recently, so maybe this slipped through. 

Any ideas on what to do? Reading through the docs, Lobster seems pretty neat.

**Comment by aardappel** [comment]
Which version of XCode are you on?

**Comment by aardappel** [comment]
I just tried with 10.2 and it builds.

If you're on an old XCode it be good to update.. or if that is not possible I can add a pre-made exe to the releases page.

**Comment by aardappel** [comment]
Also just fixed the error on the iOS build.. not that you should need it. lobster_release is the target to build.

**Comment by joerimmer** [comment]
Ah, yeah - that fixed it. I was on Xcode 9.2.

Thanks for the help.
