### ISSUE TITLE
Wrong error report when “multiple return” misusage

### ISSUE THREAD

**Issue by inferrna** [aardappel/lobster#322]
1. Wrong parameters passing,
```python
def help(x, y) -> int, int:
    return "hi", 5

let a, b, c = help(2)
```
 complains about caller at line 13: works fine
```python
tut2.lobster(13): error: cannot implicitly bind type variable `B` in call to `help` (argument doesn't match?)
```

2. Wrong returns usage,
```python
def help(x, y) -> int, int:
    return "hi", 5

let a, b, c = help(2,1)
```
 switched caller line (13) and function definition line (11): works wrong
```python
tut2.lobster(11): error: `multiple return` returns 2 values, 3 needed
  in tut2.lobster(13): help(x:int, y:int) -> int, int
```

**Comment by aardappel** [comment]
Case 1 was fixed, now says `error: no version of function "help" takes 1 arguments`

Case 2 is as I would expect it.. how would you like this error to be different?

Note that Lobster typechecks each function based on the caller, in this case the caller is expecting there to be 3 return values, and it comes across a return statement only returning 2, and flags that as an error.

**Comment by inferrna** [comment]
I was ok with case 1, but now error message is even better, thanks. 
Case 2: look to the line numbers.
![image](https://github.com/user-attachments/assets/c2a65b29-be82-4f8a-bfed-db1dbeb7938b)
![image](https://github.com/user-attachments/assets/9d6bd285-abba-44dd-a9b0-509180ec58b6)

Comparing to case 1, case 2 complains about function itself instead of caller.

To see case 2 in vscode this patch to be applied (relative to https://github.com/aardappel/lobster/pull/321 )
```diff
diff --git a/dev/lsp/src/lobster.ts b/dev/lsp/src/lobster.ts
index 4368a53..0202820 100644
--- a/dev/lsp/src/lobster.ts
+++ b/dev/lsp/src/lobster.ts
@@ -72,13 +72,13 @@ export async function parseLobster(
             return []; // TODO make "can't open file" a normal error instead of an unformatted error
         }
 
-        const regex = /^(.*)\((\d+)\): (warning|error): (.*)/g;
+        const regex = /^(.*)\((\d+)\): (warning|error): (.*)/gm;
         let match;
         const output: Diagnostic[] = [];
 
         while ((match = regex.exec(input))) {
             const at = match[1];
-            if (!file.endsWith(at)) return [];
+            //if (!file.endsWith(at)) return [];
 
             const line = parseInt(match[2]) - 1; // Its zero based
             const messageType = match[3].trim();
```

**Comment by aardappel** [comment]
Read my explanation in the last message.

The way the language works, the function is the problem, not the caller :)

**Comment by inferrna** [comment]
Whatever, I sort of fixed it on LSP side, will ship after https://github.com/aardappel/lobster/pull/321.
![image](https://github.com/user-attachments/assets/ac197b64-2710-4fc7-9209-2cf6d34700d5)
