### ISSUE TITLE
Example doesn't work properly it just flashes.  samples/platform/t2s.lobster

### ISSUE THREAD

**Issue by JudgeGroovyman** [aardappel/lobster#333]
# Background
I ran all of the samples and am very impressed with all of them but `samples/platform/t2s.lobster` is the only one that doesn't work for me.

# What does it do?
It just pops up a blank black window which flashes grey at maybe 10hz or something.  the title bar says "press the spacebar?" but pressing the spacebar doesn't do anything either.

![Lobster Shooter doesnt work](https://github.com/user-attachments/assets/bcd7cb08-c700-424f-9840-22bc4a08c08c)

# How did I run it?
I ran it just like the rest by typing `./lobster ../samples/platform/t2s.lobster` from the bin folder of my build.  I am on 2020 M1 Macbook air running MacOS Sonoma 14.5.  

# How can I help?
I can make a little screen recording if that would help or can test or attempt any fix ideas you have.  let me know what I should try.

**Comment by aardappel** [comment]
The text to speech stuff has so far only been implemented for Windows.

**Comment by JudgeGroovyman** [comment]
gotcha
