### ISSUE TITLE
The switch operator requires a 'default' case, even when all possible variants are explicitly defined. 

### ISSUE THREAD

**Issue by inferrna** [aardappel/lobster#336]
![image](https://github.com/user-attachments/assets/e2bfec77-48cf-42c3-96dc-b4488076a9d6)

This can lead to potential issues when adding new variants in the future, as they might be unintentionally masked by the _default_ case.

For example, consider an enum with values **foo** and **bar**. If a default case is included, adding a new value like **baz** might be overlooked, as it would be handled by the existing _default_ case.

It would be beneficial to have the option to either explicitly define all cases, including a _default_ case for future additions, or to omit the _default_ case entirely, forcing the inclusion of a specific case for each new variant.

**Comment by aardappel** [comment]
This is a problem with enums in particular. Enums are "typed integers", but nothing requires these values to be in range.

(and `bool` is defined as an enum with 2 values in `stdtype.lobster`, it is not a built-in type).

Currently, this is possible:

```
let my_bool = bool(read_int_from_disk())
let s = switch my_bool:
    case true: "true"
    case false: "false"
```

Let's say it reads the value `2` from disk, what should the switch do?

You could argue the `bool()` cast should.. produce a runtime error, but integer to enum casts typically don't produce errors in programming languages. And there's quite a few other ways in which enums out of range could be produced.

Imagine you store an enum on disk as part of a file format. Now the code removes a case or changes a value, such that the stored value becomes invalid. Do you still want to be able to read the file? Is a runtime error appropriate?

Maybe the switch throws a runtime error? That has the same problem with reading enums from a file.

Switches do support exhaustive matching, for example this does not require a default:

```
abstract class A
class B : A
class C: A
switch a_value:
    case B:
    case C:
```

**Comment by aardappel** [comment]
Looks like C/C++/C#/Go all work much like current Lobster in allowing illegal values in enums. Rust, Java and Swift are examples of statically typed languages that prevent such enum values being created as part of the language.

The more I think about it, the more I think that `switch` throwing a runtime error on a value out of range when no `default` is present is the "least bad" solution. It will allow the compiler to check for exhaustive use of enums in the majority of cases where an enum is guaranteed in range (does not come from a file or unsafe cast). Only code that deals with enums coming from files may need to use `default`, and they will be reminded they need it by a runtime error.

**Comment by aardappel** [comment]
Fixed here: https://github.com/aardappel/lobster/commit/d5df7970aaf37955e8c7cd629c74d8c98991885c

The test cases illustrate the new situation well:

```
    // Similarly, enums need to be checked exhaustively. A compile time error will result
    // if any enum value is not covered.

    let btests = [ true, false /*, bool(2)*/ ]

    let results5 = map(btests) t:
        switch t:
            case true: "t"
            case false: "f"
            // No default needed!
            // If bool(2) is a possible value, this switch will generate a runtime error.

    assert equal(results5, [ "t", "f" ])

    let btests2 = [ true, false, bool(2) ]

    let results6 = map(btests2) t:
        switch t:
            case true: "t"
            case false: "f"
            default:
                // Unlike class instances which can't be forged, it is possible to cast any
                // integer to an enum. This must generally be possible to load files that may
                // have old/incorrect enum values stored.
                // If this is possible, a default case should be used, since in the switch above
                // this one, a lack of a default case will result in a runtime error if an
                // illegal value is used.
                // Of course, a default case has the disadvantage that you will not get errors
                // about new enum values not having their own case.
                "?"

    assert equal(results6, [ "t", "f", "?" ])
```

**Comment by inferrna** [comment]
Thank you, now it looks much more convenient. So, now we have a choice — to be more or less strict when matching enums.

![image](https://github.com/user-attachments/assets/f2570838-6c44-47d9-8d50-0f70c4b9a7ea)
![image](https://github.com/user-attachments/assets/0250004d-9201-4eab-bf48-21a1abbb4591)
![image](https://github.com/user-attachments/assets/b4d8f314-3d34-46ab-8653-41f2884555be)

**Comment by aardappel** [comment]
Yup exactly :)
