### ISSUE TITLE
C-style cheat sheet obsolete?

### ISSUE THREAD

**Issue by jacereda** [aardappel/lobster#35]
I can't make `:=` or `:==` to work... Is the cheat sheet obsolete?

**Comment by aardappel** [comment]
It is, sorry. Only `let` and `var` syntax work. I got too many complaints from people that they hated this syntax.

**Comment by aardappel** [comment]
@kyoto-shift is updating this file as we speak, see https://github.com/aardappel/lobster/pull/32

**Comment by jacereda** [comment]
Oh, right, closing. Thanks.
