### ISSUE TITLE
Anonymous function syntax

### ISSUE THREAD

**Issue by jacereda** [aardappel/lobster#37]
Computer says no for all of the following:

```
let id1 = : _
let id2 = x: x
let id3 = (x): x
let id4 = function(x): x
```

What am I doing wrong?

**Comment by aardappel** [comment]
That syntax only works when it is following a function call.
To make a free-standing anonymous function, you have to start it with `def`, like a normal function decl, e.g.

    let id = def(x): x

**Comment by jacereda** [comment]
So, are these buggy?

```
def adder(x): return def(y): x + y
print(adder(1)(20)) // test.lobster(2): error: identifier expected, found: 20
let add1 = adder(1)
print(add1(20)) // prints 20??
```

**Comment by aardappel** [comment]
Not sure about the error.. it may be that I have limitations on directly calling it, but even if I do, it should give a better error. Will look into it.

As for the second one, Lobster does not support "escaping" lambdas (ones that use variables that are not in scope anymore), and for whatever reason I never bother to check for it. This should also become an error.

**Comment by aardappel** [comment]
Lobster supports the function call syntax e.g. `f(args) (a, b): a+b` which is why it is saying "identifier expected" for `adder(1)(20)`. So to call a lambda you'll have to do so via a variable. I'll have to see if a better error can be generated.

**Comment by jacereda** [comment]
So, what would be the idiomatic way to implement `adder`? I came up with:

```
def adder(x, k): return x + k()
def add1(x): return adder(1):x
```

**Comment by aardappel** [comment]
Except in that case, `add1` doesn't return a function, it just returns a result.

There's no way to keep a value in a function closure. Lobster's lambdas can have free variables, but it references ones currently in scope directly. The advantage is that lambdas are just as fast as regular function calls, in fact they are almost always inlined.

To implement something which keeps state, you'll have to actually implement an object:

    class adder:
        x:int
        def add(y): return x + y
    let add1 = adder { 1 }
    add1.add(20)

**Comment by aardappel** [comment]
Added a quick error check that would have caught your buggy example: https://github.com/aardappel/lobster/commit/8f51953703015caca18367d7cd401b414534011f

**Comment by jacereda** [comment]
Nice, thanks.
