### ISSUE TITLE
Bool support

### ISSUE THREAD

**Issue by jacereda** [aardappel/lobster#38]
Wouldn't the `imgui` reflection benefit from having a bool type to turn those into toggles?

**Comment by aardappel** [comment]
Yes, bools as actual types is planned https://github.com/aardappel/lobster/blob/master/dev/TODO.txt#L126

**Comment by jacereda** [comment]
Just curious, what will that look likl? Will you have a `V_BOOL` or will it be a type aliased int?

**Comment by aardappel** [comment]
Still thinking about the best approach. V_BOOL would be the strongest, but would require lots of code changes, both in the implementation and the calling code. Potential duplication of built-in functions that work on ints, etc.

One way to slightly simplify that is to make it V_BOOL in the type checker, but still V_INT in the VM.

The alternative would be stronger typed enums, which I was thinking of adding anyway. Any `int` in the type system would be tagged with an enum it belongs to. You can freely convert these to regular ints, but int -> enum requires an explicit type coercion (similar to currently `int(f)` and `float(i)` you'd have `myenum(i)`). Then, `bool` could be an enum with values `false` and `true`, defined in stdtype.lobster

**Comment by aardappel** [comment]
So we now have strongly typed enums and bool (bool is just another enum), and they work with printing, parsing, and imgui.

Search for "enum" in the http://aardappel.github.io/lobster/language_reference.html

Check all recent commits with "enum" in them for details: https://github.com/aardappel/lobster/commits/master
