### ISSUE TITLE
Windows: The build tools for llvm cannot be found

### ISSUE THREAD

**Issue by s-oram** [aardappel/lobster#41]
I'm attempting to build Lobster on Windows using Visual Studio 2019 Community Edition.

I've installed Visual Studio and loaded `lobster.sln` as directed by the getting started instructions.

Visual Studio fails to build the solution and reports an error
> The build tools for llvm (Platform Toolset = 'llvm') cannot be found. To build using the llvm build tools, please install llvm build tools. Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selection "Retarget Solution".

I've tried installing some Clang / LLVM things but it hasn't helped. 
http://releases.llvm.org/download.html  (The windows 32bit build)
https://github.com/zufuliu/llvm-utils

Is there something else I should install?

**Comment by aardappel** [comment]
No you don't need LLVM. I was experimenting with LLVM, and probably accidentally saved that in the project files.

Right-click the `language project`, Properties, General, Platform Toolset: VS 2019

Or just pull if you got the files via git, as I just fixed the files there also.

**Comment by s-oram** [comment]
Thanks Aardappel! I've pulled down the latest changes and Lobster now builds the Release x64 configuration without errors. (FYI The Release x32 configuration failed and reported errors, not sure if that is a problem or not). 

I'll try following the shooter tutorial now. :)

**Comment by aardappel** [comment]
Ah yes, I never use the 32-bit builds anymore, so those occasionally break. Fixed also, thanks :)
