### ISSUE TITLE
[doc] http://strlen.com/lobster/ - outdated explanation? outdated example?

### ISSUE THREAD

**Issue by grinapo** [aardappel/lobster#46]
> gl_scalevec allows us to scale all rendering by…

Only the example does not use `gl_scalevec`. ;-)
By looking at the explanation it feels like missing a few more sentences anyway.

**Comment by aardappel** [comment]
Fixed, thanks!

What sentences are missing?

**Comment by grinapo** [comment]
Nothing serious, just as for the first intro I would liked to see as much explanation as possible, and since I am not familar with opengl ... ;-)
It's good, I'm sure other docs explain it in depth. (Just found the language since google's FlatBuf supports it and I have never heard about it...)
You can close at will. Thank you!

**Comment by aardappel** [comment]
Ahh ok.. yeah going into detail about graphics programming might be a bit much for the front page. This provides more detail: http://aardappel.github.io/lobster/shooter_tutorial.html
