### ISSUE TITLE
building on linux: stb_image.c

### ISSUE THREAD

**Issue by faassen** [aardappel/lobster#5]
I got this to build on linux 64 bits (I think, I haven't gotten anything to actually run yet). I had to hand-compile a SDL2 recent enough to work. I did run into one snag:

The default makefile does this:

cc    -c -o ../lib/stb_image.o ../lib/stb_image.c

For me it fails then, because it builds it as a 64 bit .o file by default, and that won't work as lobster apparently wants 32 bits. To fix this I hand-compiled it with the -m32 switch first. Perhaps this can be solved in the Makefile.

**Comment by aardappel** [comment]
It now can build in 64bit mode on 64bit linux, see https://htmlpreview.github.io/?https://raw.githubusercontent.com/aardappel/lobster/master/lobster/docs/implementation.html
