### ISSUE TITLE
can't open file: stdtype.lobster

### ISSUE THREAD

**Issue by zzz6519003** [aardappel/lobster#66]

**Comment by aardappel** [comment]
Sounds like Lobster can't find the modules. Normally, `modules` are in a parallel dir to the `bin` dir where the Lobster exe is.

What OS are you on? How did you build it? where are you running it from? etc.

**Comment by JakeCoxon** [comment]
I had the same issue following the bottom of http://aardappel.github.io/lobster/getting_started.html for pre-built OSX but it seems like build is an old version. Building from source works fine

**Comment by aardappel** [comment]
Yes, this is the first file its trying to load, so it indicates a problem with paths.

And yes, I haven't made a pre-made OSX in forever, so that is very old. Where did you find it?

**Comment by JakeCoxon** [comment]
I just followed the link to https://github.com/aardappel/lobster/releases and downloaded the top link without looking at the date, saw the error and came here. I managed to build in XCode now anyway, should the binary be able to run on a different mac I have?

**Comment by aardappel** [comment]
Ah thanks, hadn't noticed that those were still there. This project currently doesn't do regular binary releases, I prefer people to just build from latest source.

To not be confusing, I deleted those 2 old binary releases. Sadly, it still shows a list of tags, which might give people the impression those are somehow more official than latest. I put a more recent tag just in case anyone downloads from there... there's apparently no way to turn this off on github.

**Comment by aardappel** [comment]
Ok, I guess this works: https://github.com/aardappel/lobster/releases

**Comment by zzz6519003** [comment]
girls love to eat lobster XD
