### ISSUE TITLE
Feature request: choose random element

### ISSUE THREAD

**Issue by kriskowal** [aardappel/lobster#67]
This is a request for design feedback before submitting a change.

A “choose one from vector” method would be handy in the standard library.

```
def foo(xs): xs[rnd(length(xs))]
```

I’ll follow up with some messages we can 👍 or 👎 for specifics details.

**Comment by kriskowal** [comment]
Option: name the method `pick`

**Comment by kriskowal** [comment]
Option: name the method `choose`

**Comment by kriskowal** [comment]
Option: overload `rnd`

**Comment by kriskowal** [comment]
Option: export from standard library

**Comment by kriskowal** [comment]
Seems like there will be an opportunity to also provide another overload like `foo([1, 2, 3], 2)` might yield `[1, 2]`, `[2, 3]`, or `[1, 3]`.

**Comment by aardappel** [comment]
I'd suggest `rnd_pick` since we already have a family of `rnd` functions.

We could add it to `std`, but its so common I can also just add it to the builtins.

**Comment by aardappel** [comment]
Decided in the end to just add them to `std`, since I also had use for a 2D version in my private code: https://github.com/aardappel/lobster/commit/290203359dc16f60b96c709587185075a5cef110
