### ISSUE TITLE
Recursion and multiple value return

### ISSUE THREAD

**Issue by dcurrie** [aardappel/lobster#73]
This fails to compile:

```
def return3oe(x):
    if x > 0:
        return return3oe(x-1)
    else:
        return 1, 2, 3
```

Whereas this equivalent version works:

```
def return3oe(x):
    if x <= 0:
        return 1, 2, 3
    else:
        return return3oe(x-1)
```

**Comment by kriskowal** [comment]
Interesting that the version that recurs is in tail position. Perhaps the first return is informing the parser about the return types of `return3oe`, and if the recursion appears first, the parser can’t infer the return type of `return3oe(x - 1)`.

**Comment by aardappel** [comment]
Yes, it has some limitations on inferring return types of recursive functions: when it encounters the first call to `return3oe` it has no idea yet what the function could be returning. Not sure if there is a solid way to avoid this.

I was going to recommend to use explicit return types, e.g.: `def return3oe(x) -> int, int, int:` but I just checked it only parses one return type, oops! Let me fix that first..

**Comment by dcurrie** [comment]
Is it possible to specify explicit return types for functions that take generic types? [My original problem that prompted this report was with a function operating on a class with generic parameters.] Type variables are supported in class definitions, but not in function signatures... at least I couldn't find a syntax that the compiler accepts. But even without generic type parameters perhaps 
```
def fun(x) -> undefined, undefined, undefined:
```
or
```
def fun(x) -> tuple
````
?

**Comment by aardappel** [comment]
Nope it is not. I need to get around to just actually add type variables.

**Comment by aardappel** [comment]
being able to declare multiple return types fixed here: https://github.com/aardappel/lobster/commit/b0b0e6dd232cc7579b1ce48151a0f16c7c19e0db

This still does not work with generic types, that will be fixed separately (this is is a much bigger change)

**Comment by aardappel** [comment]
Being able to declare generic for functions and (multiple) return types implemented here: https://github.com/aardappel/lobster/commit/87418e9858c7cc86843ede87024aa58e412e11aa

(if you search for .md and .lobster in that commit you can find examples, including an explicit generic multiple return test)
