### ISSUE TITLE
Function pointers can't be nilable?

### ISSUE THREAD

**Issue by jcorbin** [aardappel/lobster#80]
Contrived example:
```
def no_fun(a:int) -> int

var ynot : no_fun? = nil
```

Yields: `foo.lobster(3): error: value types can't be made nilable`

More realistic examples, like an array of nilable optional behavior pointers:
```
var behavior = []::no_fun?
```

Also fail with the same problem.

So you can have a nilable class and sentinel method, but not a nilable function pointer? Bogus! ;-)

**Comment by aardappel** [comment]
Yup, that's by design, a function pointer is just that, an opaque scalar that indicates a function (by index or pointer). Only reference types are nillable.

Wrap in a class if you really need such a thing? Or define a `null_function` ? :)

**Comment by J0eCool** [comment]
Does that work? I tried:
```lobster
private def FuncType() -> void
def null_func():
    return
var f: FuncType = null_func
print "uh-oh"
```
and I get
```
scratch.lobster(4): error: unknown identifier: null_func
```
which seems, not correct.

**Comment by aardappel** [comment]
Yes, there is no support for using named functions as function values atm. I should fix that.

Funnily enough, I get a different error, maybe you're not up to latest:
`test.lobster(4): error: too many arguments passed to function null_func`

Something like this does work: `var f: FuncType = def(): return`

**Comment by aardappel** [comment]
For now I've improved the error:
`test.lobster(4): error: can't use named function as value: null_func`

https://github.com/aardappel/lobster/commit/d8d3050df063334610095e863924ab1b6da795e7
