### ISSUE TITLE
Regression for 

### ISSUE THREAD

**Issue by kriskowal** [aardappel/lobster#85]
Prior, I believe, to the introduction of generics for functions, a method shared through a generic base class was valid. Now, it appears that the first class to declare the method wins the race to declaring a method with the context object’s type.

```python
class qux:
class quux:

class base<T>:
    def method():
        print "hi"

class foo: base<qux>
class bar: base<quux>

let f = foo{}
let b = bar{}

b.method()
f.method()
```

```
temp.lobster(15): error: "method" (1st argument) requires type: bar, got: foo
```

I’m not entirely certain that this *should* work, since this is likely fallout from combining dynamic dispatch and generics in the same language. I recall running into similar problems in C++ when I used virtual functions and generics together, though in C++, the programmer decides whether to use inline/generic or virtual and it’s on their head if they explode when mixed. I suspect Lobster might be better off without dynamic dispatch at all.

**Comment by aardappel** [comment]
Yes, I completely reworked how generics are represented in the compiler, so there are possibly side effects :)

I would not see we don't need dynamic dispatch at all, it is useful for some things, and I use it occasionally. It could be replaced by ADTs with switch working on them, but for somethings old fashioned OO-style dynamic dispatch is neatest. It has already been greatly simplified (and sped up) from the multi-methods we used to have, so I believe they are no "cost" to have in the language.

I definitely already had a TODO on how the two systems interact, so let me have a look at your example.

**Comment by aardappel** [comment]
Fixed, thanks! https://github.com/aardappel/lobster/commit/3d4f227039649a2c01e9efa323ab5466ef1417f4
