### ISSUE TITLE
unprintable character in string constant

### ISSUE THREAD

**Issue by dcurrie** [aardappel/lobster#88]
Using string constant `" ≈ "` gives error: unprintable character in string constant.

It looks like lex.h is testing with `if (c < ' ') Error(...` which is rejecting valid UTF8.

Workaround: `""" ≈ """`

**Comment by aardappel** [comment]
I agree we should support UTF-8 also in regular string constants, let me fix that..

**Comment by jcorbin** [comment]
The other workaround of course is `unicode_to_string`, as in `let bank = unicode_to_string([0x1F3E6]) // 🏦`.

While we're at it @aardappel, can we please get normal `\uXXXXX` escape syntax? For various reasons, you don't always want to actually have the literal codepoint(s) as they don't play well with all editors / terminals / etc.

**Comment by aardappel** [comment]
Fixed: https://github.com/aardappel/lobster/commit/e4508ed8ebd869e63eef3f7f234e53165d80ca1f

Now allows: `assert "⺆㋇䬈" == "\u2E86\u32C7\u4B08"`
