### ISSUE TITLE
hash for non-reference values

### ISSUE THREAD

**Issue by dcurrie** [aardappel/lobster#89]
The (auto generated) builtin functions reference says:
```
hash(x) -> int | hashes any value into an int
```
but this:
```
    assert hash(1) is int
```
gives:
```
error: "hash" (x argument) requires type: reference type, got: int
```
and the same problem for `float` args.

I work around it for now with 
```
if key is int: key else: if key is float: hash(string(key)) else: hash(key)
```

**Comment by aardappel** [comment]
In older versions of Lobster, `int` & `float` would automatically be converted to a reference `any` value when needed, such as with this function. That type has since been removed. To re-enable hashing on these types, we'd simply need to add overloads to this function.

A hash of an int should typically just be the identity function though, and for floats just its bit-pattern representation, so not sure how useful this is beyond very generic code?

**Comment by dcurrie** [comment]
> not sure how useful this is beyond very generic code

Yes, that is exactly the situation, a generic hash table.

> we'd simply need to add overloads to this function

I assume you mean in C++, because in Lobster: 
```
private def hash(i: int) -> int: i
```
gives
```
error: cannot override built-in function: hash
```

**Comment by aardappel** [comment]
Yes, in `builtins.cpp`.. very similar to `length` and other overloaded functions. I can add it, but you can also create a PR if you feel so inclined.

**Comment by dcurrie** [comment]
I tried this:
```
nfr("hash", "x", "L", "I",
    "hashes a function value into an int",
    [](VM &vm, Value &a) {
        auto h = a.Hash(vm, V_FUNCTION);
        return Value(h);
    });
nfr("hash", "x", "I", "I",
    "hashes an int value into an int; may be the identity function",
    [](VM &vm, Value &a) {
        auto h = a.Hash(vm, V_INT);
        return Value(h);
    });
nfr("hash", "x", "F", "I",
    "hashes a float value into an int",
    [](VM &vm, Value &a) {
        auto h = a.Hash(vm, V_FLOAT);
        return Value(h);
    });
nfr("hash", "x", "A", "I",
    "hashes any ref value into an int",
    [](VM &vm, Value &a) {
        auto h = a.ref()->Hash(vm);
        return Value(h);
    });
```
but I still get
```
bin/lobster --gen-builtins-html ../e/lobster-rosetta/util/RobinHoodHashmapTest.lobster 
RobinHoodHashmap.lobster(63): error: "hash" (x argument) requires type: reference type, got: int
```
I included the `--gen-builtins-html` to confirm I'm using the new builtins (I am). I don't get how `NativeFun`'s arg type is used for dispatch... is there a specifier for reference type that's less general the `"A"`?

**Comment by aardappel** [comment]
Looks like the code is being dumb and picking the last one that matched: https://github.com/aardappel/lobster/blob/master/dev/src/lobster/typecheck.h#L2566

So put the `A` function first, and see if that improves it :)

**Comment by dcurrie** [comment]
This version gives the same error:
```
nfr("hash", "x", "A", "I",
    "hashes any ref value into an int",
    [](VM &vm, Value &a) {
        auto h = a.ref()->Hash(vm);
        return Value(h);
    });
nfr("hash", "x", "L", "I",
    "hashes a function value into an int",
    [](VM &vm, Value &a) {
        auto h = a.Hash(vm, V_FUNCTION);
        return Value(h);
    });
nfr("hash", "x", "I", "I",
    "hashes an int value into an int; may be the identity function",
    [](VM &vm, Value &a) {
        auto h = a.Hash(vm, V_INT);
        return Value(h);
    });
nfr("hash", "x", "F", "I",
    "hashes a float value into an int",
    [](VM &vm, Value &a) {
        auto h = a.Hash(vm, V_FLOAT);
        return Value(h);
    });
```
The logic in the loop you referenced is pretty convoluted.  It seems to match type Any, or type [Any] for vector actuals,  or actual `ConvertsTo` the  parameter type, assuming a lot about the way `ConvertsTo` and `ActualBuiltinType` work. Once a match is found, the loop `break`s -- so, I would have guessed it would choose the first to match, but of course that depends on the order of the overloads in the `cnf->overloads` linked list... which might be the reverse of the order in the source file. Yet neither order seems to work. Ok, looking at the logic in `NativeRegistry` I see
```
        if (existing) {
            if (/*nf->args.v.size() != existing->args.v.size() ||
                nf->retvals.v.size() != existing->retvals.v.size() || */
                nf->subsystemid != existing->subsystemid ) {
                // Must have similar signatures.
                assert(0);
                THROW_OR_ABORT("native library name clash: " + nf->name);
            }
            nf->overloads = existing->overloads;
            existing->overloads = nf;
            nf->first = existing->first;
        } else {
            nfunlookup[nf->name /* must be in value */] = nf;
        }
```
So, the first one in the source file is always the first one checked, and then they come in reverse order, so...
```
nfr("hash", "x", "I", "I",
    "hashes an int value into an int; may be the identity function",
    [](VM &vm, Value &a) {
        auto h = a.Hash(vm, V_INT);
        return Value(h);
    });
nfr("hash", "x", "A", "I",
    "hashes any ref value into an int",
    [](VM &vm, Value &a) {
        auto h = a.ref()->Hash(vm);
        return Value(h);
    });
nfr("hash", "x", "L", "I",
    "hashes a function value into an int",
    [](VM &vm, Value &a) {
        auto h = a.Hash(vm, V_FUNCTION);
        return Value(h);
    });
nfr("hash", "x", "F", "I",
    "hashes a float value into an int",
    [](VM &vm, Value &a) {
        auto h = a.Hash(vm, V_FLOAT);
        return Value(h);
    });
```
works!

I'll create a PR.

**Comment by aardappel** [comment]
I'll need to check if I can simplify that order, since clearly this isn't very workable. Thanks for figuring it out :P

**Comment by JakeCoxon** [comment]
@dcurrie did you manage to implement a hash map? I'm trying to add one as a resource with an underlying unordered_map but struggling a bit. How did you do it?

**Comment by dcurrie** [comment]
@JakeCoxon See [the implementation on github](https://github.com/dcurrie/lobster-rosetta/blob/master/util/RobinHoodHashmap.lobster)

**Comment by JakeCoxon** [comment]
@dcurrie amazing! thanks

**Comment by aardappel** [comment]
btw, note that for simple cases of "dictionary look ups", you can use the built-in `binary_search` function, that works on any sorted vectors. It is not going to be as fast as a hash table for larger tables, but since its all in C++, its going to be competitive against a Lobster hash table anything medium size (~hundred elements?)

I've never added a native dictionary type, since Lobster's focus on graphics/games doesn't have a lot of natural uses.. but that could also be considered.

Adding new type as `resource` is an easy escape hatch, but you'd have to be careful with making it store Lobster values in terms of reference counting etc.

**Comment by JakeCoxon** [comment]
@aardappel Thanks for the tip! My use case was a sparse grid of entities keyed by their cell position. I think I'm too used to thinking in python but keeping a sorted list of entities turned out to be a lot simpler, and it ended up being useful for rendering as well

**Comment by aardappel** [comment]
We have hashing in scalars now, this can be closed.
