### ISSUE TITLE
Crash in dirbrowse demo app

### ISSUE THREAD

**Issue by mzaks** [aardappel/lobster#95]
I am running Lobster (master branch) on macOS (10.13.6)
When clicking on a folder in the dirbrowse app I get:
```
Assertion failed: (i < len && width == 1), function At, file ../../src/lobster/vmdata.h, line 623
```

**Comment by aardappel** [comment]
Thanks for reporting! That seems a regression in some of the lifetime stuff, I know how to fix it.. will get to that later.

**Comment by aardappel** [comment]
Fixed: https://github.com/aardappel/lobster/commit/2e75f1027b5ccb7b93d7ab1f4ad2f13f27d74055
See commit description :)
